xcodeproj: ./fr-swift.xcodeproj
scheme: fr-swift
ignore:
  - fr-swift/AppDelegate.swift
  - fr-swift/Environment.swift
  - fr-swift/Services/RollbarService.swift
  - fr-swiftTests/*
  - fr-swiftUITests/*
